title: Sergii's blog
email: blue-common-garter-snake-b086@k6.ee
description: >
  This is a technical blog with random thoughts and pet projects.
baseurl: "" 
url: ""
github_username: msergo

# Build settings
theme: minima
plugins:
  - jekyll-feed